// src/app/components/white-header/white-header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-white-header',
  imports: [],
  templateUrl: './white-header.component.html',
  styleUrl: './white-header.component.scss'
})
export class WhiteHeaderComponent {

}

<nav class="nav">
  <a href="">MURASAKI</a>

  <div>
    <section>
      <a href="">Sobre</a>
      <a href="">Aulas</a>
      <a href="/subscription">Planos</a>
      <a href="">Comunidade</a>
    </section>

    <button class="header-button">Entrar</button>
  </div>
</nav>

// src/components/white-header/white-header.tsx
import { Link } from "react-router-dom";
import "./white-header.scss";

const WhiteHeader = () => {
  return (
    <nav className="white-nav">
      <Link to="/">MURASAKI</Link>

      <div>
        <section>
          <Link to="">Sobre</Link>
          <Link to="">Aulas</Link>
          <Link to="/subscription">Planos</Link>
          <Link to="">Comunidade</Link>
        </section>

        <button className="white-header-button">Entrar</button>
      </div>
    </nav>
  );
};

export default WhiteHeader;
