// src/pages/subscription/subscription.tsx
import { useEffect, useState } from "react";
import SubscriptionCard from "../../components/subscription-card/subscription-card";
import WhiteHeader from "../../components/white-header/white-header";
import { getAllPlansService } from "../../services/plans.service";
import "./subscription.scss";
import Footer from "../../components/footer/footer";

interface Plan {
  id: string;
  title: string;
  description: string;
  value: number;
  advantages: string[];
}

const Subscription = () => {
  const [plans, setPlans] = useState<Plan[]>([]);

  const getAllPlans = async () => {
    try {
      const response = await getAllPlansService();
      setPlans(response.data);
    } catch (error) {
      console.error("Error fetching plans:", error);
    }
  };

  useEffect(() => {
    getAllPlans();
  }, []);

  return (
    <>
      <WhiteHeader />
      <div className="sub">
        <h1>Escolha o plano ideal para você</h1>

        <section>
          {plans.map((plan) => (
            <SubscriptionCard
              key={plan.id}
              title={plan.title}
              value={plan.value}
              description={plan.description}
              advantages={plan.advantages}
            />
          ))}
        </section>
      </div>
      <Footer />
    </>
  );
};

export default Subscription;

// src/app/pages/subscription/subscription.component.ts
import { Component } from '@angular/core';
import { FooterComponent } from '../../components/footer/footer.component';
import { SubscriptionCardComponent } from '../../components/subscription-card/subscription-card.component';
import { WhiteHeaderComponent } from "../../components/white-header/white-header.component";

@Component({
  selector: 'app-subscription',
  imports: [WhiteHeaderComponent, SubscriptionCardComponent, FooterComponent],
  templateUrl: './subscription.component.html',
  styleUrl: './subscription.component.scss',
})
export class SubscriptionComponent {}

<app-white-header />

<div>
  <h1>Escolha o plano ideal para você</h1>

  <section>
    <app-subscription-card />
    <app-subscription-card />
    <app-subscription-card />
    <app-subscription-card />
  </section>
</div>

<app-footer />
