// src/pages/dashboard/dashboard.tsx
import WhiteHeader from "../../components/white-header/white-header";
import "./dashboard.scss";

const Dashboard = () => {
  return (
    <div>
      <WhiteHeader />
      <div className="dashboard-area">
        <section className="side-bar">
          <button>Overview</button>
          <button>
            <i className="fa-solid fa-users"></i>Users
          </button>
          <button>Lessons</button>
          <button>
            <i className="fa-solid fa-coins"></i>Plans
          </button>
          <button>
            <i className="fa-solid fa-file"></i>Reports
          </button>
          <button>Backlog</button>
        </section>
      </div>
    </div>
  );
};

export default Dashboard;

// src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { FooterComponent } from "../../components/footer/footer.component";

@Component({
  selector: 'app-dashboard',
  imports: [FooterComponent],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss'
})
export class DashboardComponent {

}

<!-- <app-black-header/> -->

<div class="dashboard">
	<div class="side-bar">
		<section>
			<h1>Dashboard</h1>
			<button>Home</button>
			<button>Create Lesson</button>
			<button>Manage Lessons</button>
			<button>Manage users</button>
			<button>Reports</button>
			<button>Overview </button>
			<button>Logs</button>
			<button>Back</button>
		</section>
		
	</div>
	<div></div>
</div>


<app-footer/>
